### ISSUE TITLE
Does cluttex support magic comments to specify the engine?

### ISSUE THREAD

**Issue by ShotaroTsuji** [minoki/cluttex#1]
I often make mistake that specifies the wrong engine for my LaTeX files.
So I want to specify the engine in the head of the LaTeX file.
Is there any support for such function?

**Comment by minoki** [comment]
Currently, no.

I recommend writing a shellscript or Makefile to typeset the document.

**Comment by ShotaroTsuji** [comment]
Thank you for your reply.
I agree with your direction of the usage of cluttex.
