### ISSUE TITLE
Same color for EXEC and ERROR

### ISSUE THREAD

**Issue by tsuu32** [minoki/cluttex#2]
こんにちは。最近ClutTeXを知って使ってみました。
使っていて気になったのですが、エスケープシーケンスによるカラー出力で、[EXEC]のメッセージと[ERROR]のメッセージはどちらも全く同じ色(赤)で出力されるようです。

別の色にした方がわかりやすいと思うのですが、どうでしょうか？

**Comment by minoki** [comment]
メッセージの色に関しては、そのうち設定ファイルでカスタマイズ可能にしたいと思っています。

ただ、それとは別にデフォルトの色を変えるのは良い案だと思います。変えるならどういう色がいいと思いますか？

**Comment by tsuu32** [comment]
これは経験上何となくなんですが、[ERROR]は赤がいいと思うので[EXEC]を変えるべきだと思います。

[EXEC]は緑かシアンのどっちかがいいと思いますが、決められませんでした。緑がいいのかなあとは思います。（GitHubのIssueのOpenが緑色であったため）

**Comment by minoki** [comment]
シアンにしました。
